let catalog=[];
const completedKey=code=>'pluton-completed-'+code;
const courseLanguage=()=>window.plutonLanguage?.current()||'es';
const escapeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderCourses(){const el=document.getElementById('courseList');if(!el)return;const lang=courseLanguage();document.getElementById('learningNotice').textContent=lang==='en'?'Learning activities and quiz results are saved on this device only. Educational material does not replace supervised professional training.':'Las actividades y respuestas se guardan solo en este dispositivo. El material educativo no sustituye la formación profesional supervisada.';el.innerHTML=catalog.map(c=>{let completed=[];try{completed=JSON.parse(localStorage.getItem(completedKey(c.code))||'[]')}catch(e){}return `<article id="course-${escapeText(c.code)}" class="pa-course-card"><h2>${escapeText(c[lang])}</h2><small>${escapeText(c.code)}</small><p>${lang==='en'?'Progress':'Progreso'}: ${Math.round(completed.length/c.lessons.length*100)}%</p>${c.lessons.map((l,i)=>`<details class="pa-lesson" ${completed.includes(i)?'data-done="yes"':''}><summary>${escapeText(l[lang])} ${completed.includes(i)?'✓':''}</summary><p>${escapeText(l.content[lang])}</p><p><strong>${escapeText(l.question[lang])}</strong></p>${l.options[lang].map((option,j)=>`<label class="pa-option"><input type="radio" name="quiz-${c.code}-${i}" value="${j}"> ${escapeText(option)}</label>`).join('')}<button type="button" class="pa-quiz-button" data-code="${c.code}" data-lesson="${i}">${lang==='en'?'Check answer':'Comprobar respuesta'}</button><p class="pa-feedback" aria-live="polite"></p></details>`).join('')}</article>`}).join('')}
document.addEventListener('click',event=>{const b=event.target.closest('.pa-quiz-button');if(!b)return;const c=catalog.find(x=>x.code===b.dataset.code),i=Number(b.dataset.lesson),lesson=c?.lessons[i];if(!lesson)return;const box=b.closest('details'),selected=box.querySelector('input[type="radio"]:checked'),lang=courseLanguage(),feedback=box.querySelector('.pa-feedback');if(!selected){feedback.textContent=lang==='en'?'Choose an answer first.':'Selecciona una respuesta.';return}if(Number(selected.value)!==lesson.answer){feedback.textContent=lang==='en'?'Try again.':'Inténtalo de nuevo.';return}let completed=[];try{completed=JSON.parse(localStorage.getItem(completedKey(c.code))||'[]')}catch(e){}completed=[...new Set([...completed,i])];localStorage.setItem(completedKey(c.code),JSON.stringify(completed));localStorage.setItem('pluton-progress-'+c.code,String(Math.round(completed.length/c.lessons.length*100)));feedback.textContent=lang==='en'?'Correct! Lesson completed.':'¡Correcto! Lección completada.';const summary=box.querySelector('summary');if(!summary.textContent.includes('✓'))summary.textContent+=' ✓';box.closest('article').querySelector('p').textContent=(lang==='en'?'Progress: ':'Progreso: ')+Math.round(completed.length/c.lessons.length*100)+'%'});
fetch('catalog.json').then(r=>{if(!r.ok)throw Error('Catalog unavailable');return r.json()}).then(data=>{catalog=data;renderCourses()}).catch(()=>{document.getElementById('courseList').textContent='No se pudo cargar el catálogo. / Could not load the catalog.'});

window.addEventListener('load',()=>{const code=new URLSearchParams(location.search).get('course');if(!code)return;const el=document.getElementById('course-'+CSS.escape(code));if(el){el.scrollIntoView({block:'start'});el.classList.add('pa-highlight')}});
