/* V14: Navegación rápida bilingüe, local al catálogo y páginas existentes. */
(()=>{'use strict';
const sections=[['inicio','Inicio','Home','index.html#inicio'],['cursos','Cursos','Courses','index.html#cursos'],['membresias','Membresías','Memberships','index.html#membresias'],['plataforma','Mi plataforma','My dashboard','dashboard.html'],['lecciones','Lecciones','Lessons','courses.html'],['certificados','Certificados','Certificates','index.html#certificados'],['recursos','Recursos','Resources','index.html#recursos'],['noticias','Noticias','News','index.html#noticias'],['participa','Participa','Participate','index.html#participa'],['reto','Reto del día','Daily challenge','index.html#reto'],['comunidad','Comunidad','Community','index.html#crecimiento'],['cuaderno','Mi cuaderno de estudio','My study notebook','courses.html#notesLibrary']];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fold=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase().trim();
let courses=[],open=false,active=0,results=[];
const en=()=>{try{return window.plutonLanguage?.current()==='en'||localStorage.getItem('pluton-lang')==='en'||document.documentElement.lang==='en'}catch(_){return document.documentElement.lang==='en'}};
const tr=(es,english)=>en()?english:es;
const modal=()=>document.getElementById('pa-global-search');
function render(){const root=document.getElementById('pa-search-results'),field=document.getElementById('pa-search-input');if(!root||!field)return;const q=fold(field.value);let entries=sections.map(([id,es,english,url])=>({kind:'section',id,es,english,url}));for(const c of courses){entries.push({kind:'course',id:c.code,es:c.es,english:c.en,url:'courses.html?course='+encodeURIComponent(c.code),code:c.code});for(let i=0;i<(c.lessons||[]).length;i++){const l=c.lessons[i];entries.push({kind:'lesson',id:c.code+'-'+i,es:l.es,english:l.en,url:'courses.html?course='+encodeURIComponent(c.code)+'&lesson='+i,code:c.code,courseEs:c.es,courseEn:c.en})}}
results=(q?entries.filter(x=>fold([x.es,x.english,x.id,x.code,x.courseEs,x.courseEn].join(' ')).includes(q)):entries.filter(x=>x.kind==='section')).slice(0,30);active=0;
root.innerHTML=results.length?results.map((x,i)=>`<a class="pa-search-result${i===active?' selected':''}" href="${escape(x.url)}" role="option" aria-selected="${i===active}" id="pa-search-option-${i}"><span class="pa-search-result-icon" aria-hidden="true">${x.kind==='lesson'?'▤':x.kind==='course'?'▣':'↗'}</span><span><strong>${escape(en()?x.english:x.es)}</strong><small>${escape(x.kind==='lesson'?(en()?'Lesson · ':'Lección · ')+(x.code||''):x.kind==='course'?(en()?'Course · ':'Curso · ')+x.code:tr('Sección de la plataforma','Platform section'))}</small></span></a>`).join(''):`<p class="pa-search-empty">${tr('No encontramos resultados. Prueba otro término.','No results found. Try another term.')}</p>`;
field.setAttribute('aria-activedescendant',results.length?'pa-search-option-0':'');document.getElementById('pa-search-title').textContent=tr('¿A dónde quieres ir?','Where would you like to go?');field.placeholder=tr('Buscar cursos, lecciones, noticias…','Search courses, lessons, news…');document.getElementById('pa-search-close').setAttribute('aria-label',tr('Cerrar búsqueda','Close search'));document.getElementById('pa-search-help').textContent=tr('Escribe un tema y toca un resultado.','Type a topic and select a result.');document.querySelectorAll('.pa-search-launch').forEach(b=>b.setAttribute('aria-label',tr('Abrir buscador','Open search')));
}
function launch(){const m=modal();if(!m)return;open=true;m.hidden=false;document.body.classList.add('pa-search-open');render();document.getElementById('pa-search-input').focus()}
function close(){const m=modal();if(!m)return;open=false;m.hidden=true;document.body.classList.remove('pa-search-open');document.querySelector('.pa-search-launch')?.focus()}
function setActive(n){if(!results.length)return;active=(n+results.length)%results.length;document.querySelectorAll('.pa-search-result').forEach((el,i)=>{el.classList.toggle('selected',i===active);el.setAttribute('aria-selected',String(i===active))});const el=document.getElementById('pa-search-option-'+active);document.getElementById('pa-search-input').setAttribute('aria-activedescendant',el.id);el.scrollIntoView({block:'nearest'})}
function init(){const button=document.createElement('button');button.className='pa-search-launch';button.type='button';button.innerHTML='<span aria-hidden="true">⌕</span>';button.setAttribute('aria-label','Abrir buscador');const header=document.querySelector('body > header');if(header){const toggle=header.querySelector('#languageToggle');if(toggle)header.insertBefore(button,toggle);else header.appendChild(button)}else{const main=document.querySelector('.student-dashboard > header');if(main)main.appendChild(button)}
const m=document.createElement('div');m.id='pa-global-search';m.className='pa-search-overlay';m.hidden=true;m.innerHTML='<div class="pa-search-backdrop"></div><section class="pa-search-dialog" role="dialog" aria-modal="true" aria-labelledby="pa-search-title"><div class="pa-search-head"><h2 id="pa-search-title"></h2><button type="button" id="pa-search-close" aria-label="Cerrar búsqueda">×</button></div><label class="pa-search-input-wrap"><span aria-hidden="true">⌕</span><input id="pa-search-input" type="search" role="combobox" aria-autocomplete="list" aria-controls="pa-search-results" aria-expanded="true" autocomplete="off" maxlength="120"></label><p id="pa-search-help"></p><div id="pa-search-results" role="listbox"></div></section>';document.body.appendChild(m);
button.addEventListener('click',launch);m.querySelector('.pa-search-backdrop').addEventListener('click',close);document.getElementById('pa-search-close').addEventListener('click',close);document.getElementById('pa-search-input').addEventListener('input',render);
document.getElementById('pa-search-input').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(active+1)}if(e.key==='ArrowUp'){e.preventDefault();setActive(active-1)}if(e.key==='Enter'&&results.length){e.preventDefault();location.href=results[active].url}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open){e.preventDefault();close()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open?close():launch()}});
const languageButton=document.getElementById('languageToggle');languageButton?.addEventListener('click',()=>setTimeout(()=>{if(open)render()},20));render();
fetch('catalog.json').then(r=>{if(!r.ok)throw Error('catalog');return r.json()}).then(data=>{if(Array.isArray(data))courses=data;if(open)render()}).catch(()=>{/* section navigation remains available */});
if(location.hash==='#notesLibrary'){setTimeout(()=>{const notes=document.getElementById('notesLibrary');if(notes){notes.hidden=false;notes.scrollIntoView({block:'start'})}},350)}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
