(()=>{'use strict';const categories=['salud','tecnologia','educacion'];let selected='salud';const en=()=>window.plutonLanguage?.current()==='en';const status=()=>document.getElementById('newsStatus');const list=()=>document.getElementById('newsList');const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function translateNews(){const english=en();const set=(selector,value)=>{const el=document.querySelector(selector);if(el)el.textContent=value};set('[data-news-title]',english?'News and current events':'Noticias y actualidad');set('[data-news-intro]',english?'Health, technology and education. External news headlines are updated automatically when the service is available.':'Salud, tecnología y educación. Titulares de medios externos actualizados automáticamente cuando el servicio está disponible.');document.querySelectorAll('[data-news-category]').forEach(b=>{b.textContent=({salud:english?'Health':'Salud',tecnologia:english?'Technology':'Tecnología',educacion:english?'Education':'Educación'})[b.dataset.newsCategory];b.classList.toggle('active',b.dataset.newsCategory===selected)});set('.pa-news-disclaimer',english?'Links lead to external sources. PLUTÓN ACADEMIC does not independently verify these headlines.':'Los enlaces conducen a fuentes externas. PLUTÓN ACADEMIC no redacta ni verifica independientemente estos titulares.');}async function load(){translateNews();status().textContent=en()?'Loading news…':'Cargando noticias…';list().innerHTML='';try{const r=await fetch('/api/news?category='+encodeURIComponent(selected),{headers:{Accept:'application/json'}});if(!r.ok)throw Error('News unavailable');const data=await r.json();if(!Array.isArray(data.items)||!data.items.length)throw Error('Empty');list().innerHTML=data.items.map(x=>`<article class="pa-news-card"><h3>${escape(x.title)}</h3><p>${escape(x.source||'')}</p><a href="${escape(x.link)}" target="_blank" rel="noopener noreferrer">${en()?'Read source':'Leer fuente'} →</a></article>`).join('');status().textContent='';}catch(e){status().textContent=en()?'News is temporarily unavailable. Please try again later.':'Noticias temporalmente no disponibles. Inténtalo más tarde.';}}function community(){
 const field=document.getElementById('communityIdea'),button=document.getElementById('saveIdea'),clear=document.getElementById('clearIdea'),message=document.getElementById('ideaStatus'),count=document.getElementById('ideaCount');
 if(!field||!button)return;
 try{field.value=localStorage.getItem('pluton-community-idea')||''}catch(e){}
 const translate=()=>{
  const english=en(),set=(selector,value)=>{const el=document.querySelector(selector);if(el)el.textContent=value};
  set('[data-community-title]',english?'Community question':'Pregunta de la comunidad');
  set('[data-community-intro]',english?'Share an idea to improve your learning. Your response is saved only in this browser.':'Comparte una idea para mejorar tu aprendizaje. La respuesta se guarda únicamente en este navegador.');
  set('label[for="communityIdea"]',english?'Your proposal':'Tu propuesta');
  field.placeholder=english?'What topic would you like to learn?':'¿Qué tema te gustaría aprender?';
  button.textContent=english?'Save my idea':'Guardar mi idea';
  if(clear)clear.textContent=english?'Clear my idea':'Borrar mi idea';
  if(count)count.textContent=english?`${field.value.length}/600 characters`:`${field.value.length}/600 caracteres`;
  if(message.dataset.state==='saved')message.textContent=english?'Saved on this device.':'Guardado en este dispositivo.';
  if(message.dataset.state==='cleared')message.textContent=english?'Idea cleared on this device.':'Idea borrada de este dispositivo.';
 };
 field.addEventListener('input',()=>{if(count)count.textContent=en()?`${field.value.length}/600 characters`:`${field.value.length}/600 caracteres`;});
 button.addEventListener('click',()=>{try{localStorage.setItem('pluton-community-idea',field.value.trim());message.dataset.state='saved';message.textContent=en()?'Saved on this device.':'Guardado en este dispositivo.'}catch(e){message.textContent=en()?'Unable to save.':'No se pudo guardar.'}});
 clear?.addEventListener('click',()=>{try{localStorage.removeItem('pluton-community-idea');field.value='';message.dataset.state='cleared';translate();}catch(e){message.textContent=en()?'Unable to clear.':'No se pudo borrar.'}});
 document.getElementById('languageToggle')?.addEventListener('click',()=>setTimeout(translate,0));
 translate();
}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-news-category]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.newsCategory;load()}));community();load();document.getElementById('languageToggle')?.addEventListener('click',()=>setTimeout(()=>{translateNews();const cards=list().querySelectorAll('a');cards.forEach(a=>a.textContent=(en()?'Read source':'Leer fuente')+' →')},0));});})();